# Generated by Django 5.0.4 on 2024-04-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagem_cliente_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
